### PR TITLE
Improved HLVL encounters - captcha handling - bad responses.

### PR DESCRIPTION
**Pull request by neskk**
## Description

If 2captcha automatic captcha mode is enabled (`--captcha-solving` + `--captcha-key`) and a HLVL account encounters a captcha, instead of putting the account aside RM now handles the Captcha.

Also detects bad status response from encounter and logs the errors accordingly.
Changed 'captcha' to 'failed' field in accounts that are put in the HLVL Account Set because it provides a broader semantic and acts a simple "on/off" switch for accounts.

## Motivation and Context

Seems obvious that HLVL accounts need captcha handling even if they don't get those very often.

## How Has This Been Tested?

I haven't actually tested this because I currently refuse to touch my LVL 30 accounts and even if I did, it's very unlikely that we get a captcha. Nevertheless I'm fairly confident that this should work without problems. One side effect I just remembered is that if captcha response takes too long, the SleepDelay won't be respected and will be nearly 0 because of previous changes to Schedulers.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by jorgitoh** [comment]
Mmm I like the idea, but we need an argument like hck ( high level captcha ) because in some scenarios we want to care about lvl 30 accounts but not about the lvl 2 accounts who will recieve shadowban after 3 days. Sry for my english :D

**Comment by Acadia1337** [comment]
This is a no brainer. We need captcha support on all accounts.

**Comment by tomballgithub** [comment]
`Traceback (most recent call last):
  File "runserver.py", line 20, in <module>
    from pogom.app import Pogom
  File "/root/pokemon/Rocketmap_Jun15_all/pogom/app.py", line 19, in <module>
    from .models import (Pokemon, Gym, Pokestop, ScannedLocation,
  File "/root/pokemon/Rocketmap_Jun15_all/pogom/models.py", line 37, in <module>
    from .captcha import automatic_captcha_solve
  File "/root/pokemon/Rocketmap_Jun15_all/pogom/captcha.py", line 26, in <module>
    from .models import Token
ImportError: cannot import name Token
`

**Comment by tomballgithub** [comment]
I installed the latest code with only this PR and this is result:

> Traceback (most recent call last):
  File "runserver.py", line 20, in <module>
    from pogom.app import Pogom
  File "/root/pokemon/Rocketmap_test/pogom/app.py", line 19, in <module>
    from .models import (Pokemon, Gym, Pokestop, ScannedLocation,
  File "/root/pokemon/Rocketmap_test/pogom/models.py", line 37, in <module>
    from .captcha import automatic_captcha_solve
  File "/root/pokemon/Rocketmap_test/pogom/captcha.py", line 26, in <module>
    from .models import Token
ImportError: cannot import name Token

**Comment by friscoMad** [comment]
@tomballgithub You have probably done a bad merge as Token class it is inside model.py

**Comment by tomballgithub** [comment]
OK, but has anyone else tried this?  I have never had an issue with merging and have reproduced this repeatedly.  All I am doing is the following after a new pull into a new directory

> git fetch origin pull/2078/head:l30fix
git merge l30fix

File: pogom/captcha.py [hunk 1]
```diff
@@ -23,7 +23,7 @@
 from pgoapi import PGoApi
 from .fakePogoApi import FakePogoApi
 
-from .models import Token
+import models
```
Comment (Arengo) [inline pogom/captcha.py]: Better not import our biggest file at whole
```py
from .models.Token import get_valid
```

File: pogom/models.py [hunk 2]
```diff
@@ -2116,16 +2127,13 @@ def parse_map(args, map_dict, step_location, db_update_queue, wh_update_queue,
                     'move_1': pokemon_info['move_1'],
                     'move_2': pokemon_info['move_2'],
                     'height': pokemon_info['height_m'],
-                    'weight': pokemon_info['weight_kg']
+                    'weight': pokemon_info['weight_kg'],
+                    'cp_multiplier': pokemon_info.get('cp_multiplier', None)
```
Comment (Arengo) [inline pogom/models.py]: ``cp_multiplier`` is the same construct like CP, even more since ``cp_multiplier`` directly reflects the level which results in the CP combined with carried IVs. So this should also only be parsed if encounter_level >= 30. However, since we do only encounter with level 30s either way, I guess it's best to have everything inside this update than opening another one below.

File: pogom/utils.py [hunk 3]
```diff
@@ -660,7 +660,7 @@ def get_args():
                         'auth_service': service,
                         'username': username,
                         'password': password,
-                        'captcha': False
+                        'failed': False
```
Comment (Arengo) [inline pogom/utils.py]: So, failed now means any fail and also ``captcha`` not solved in time before fetching next account?

File: pogom/captcha.py (hunk 1 above)
Comment (sebastienvercammen) [inline pogom/captcha.py]: As it was, it was better:
```
from .models import Token
```

File: pogom/models.py [hunk 4]
```diff
@@ -2015,48 +2015,59 @@ def parse_map(args, map_dict, step_location, db_update_queue, wh_update_queue,
...
+                                scan_location)
+                            responses = encounter_result['responses']
+
+                        status_code = responses['ENCOUNTER'].get(
+                                        'status', 0)
+                        if status_code != 1:
+                            # Flag account.
+                            hlvl_account['failed'] = True
+                            log.error('Account %s has failed a encounter.'
+                                      + ' Got a "%s" status response.',
```
Comment (sebastienvercammen) [inline pogom/models.py]: an *

File: pogom/models.py (hunk 2 above)
Comment (sebastienvercammen) [inline pogom/models.py]: `cp_multiplier` should stay where it was, in the level >=30 bracket.

File: pogom/models.py [hunk 5]
```diff
@@ -2015,48 +2015,59 @@ def parse_map(args, map_dict, step_location, db_update_queue, wh_update_queue,
...
+                                wh_message = {'status_name': args.status_name,
+                                              'status': 'encounter',
+                                              'mode': 'disabled',
+                                              'account': account['username'],
+                                              'captcha': status['captcha'],
+                                              'time': 0}
+                                wh_update_queue.put(('captcha', wh_message))
+                        elif len(captcha_url) > 1 and automatic_captcha_solve(
+                                args, status, api, captcha_url, account,
+                                wh_update_queue):
```
Comment (sebastienvercammen) [inline pogom/models.py]: We need to log a message and update the status message that we're going to solve the captcha for the high-level account.

**Comment by neskk** [comment]
This PR is probably gonna die, I'm reworking accounts and moving them to the database. I won't be updating this, might as well close it...

**Comment by sebastienvercammen** [comment]
@neskk This PR is next on the list. Or second, but it's at the top.

**Comment by tomballgithub** [comment]
#timing...  @Arengo is testing this right now

**Comment by Alderon86** [comment]
@tomballgithub nearly, its Alderon, but u are close :P

**Comment by tomballgithub** [comment]
Close enough?!?!

File: pogom/models.py [hunk 6]
```diff
@@ -2015,48 +2015,59 @@ def parse_map(args, map_dict, step_location, db_update_queue, wh_update_queue,
...
-                                      + ' Account will not be used.',
-                                      hlvl_account['username'])
-                        else:
-                            # Update level indicator before we clear the
-                            # response.
-                            encounter_level = hlvl_account['level']
-
-                            # User error?
-                            if encounter_level < 30:
-                                raise Exception('Expected account of level 30'
```
Comment (sebastienvercammen) [inline pogom/models.py]: This shouldn't have been removed.

**Comment by sebastienvercammen** [comment]
Closed, #2139 builds on this PR with the latest API changes.
